# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - client-tarjetacredito

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    environment: Production

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Set working directory
        run: |
          dir
          cd src\environments
          dir

      - name: Replace API URL
        run: |
          echo "API_URL es ${{ env.API_URL }} y la otra es ${{ vars.API_URL }}"
          $content = Get-Content src\environments\environment.prod.ts -Raw
          echo "valor de content 1"
          echo $content
          $content = $content -replace '#{API_URL}#', '${{ vars.API_URL }}'
          echo "valor de content 2"
          echo $content
          $content | Set-Content src\environments\environment.prod.ts
          type src\environments\environment.prod.ts

      - name: npm install, build
        run: |
          npm install -g @angular/cli@16.x
          npm install
          ng build --configuration=production
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./dist/practicaUdemy1
          overwrite: true

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'client-tarjetacredito'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_EDE01D26E9784E35A89688C102AD159E }}
